#v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wemealkit-deployment
  namespace: wemealkit
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wemealkit
  template:
    metadata:
      labels:
        app: wemealkit
    spec:
      containers:
      - name: wemealkit
        image: daikmasa/wemealkit:093e910
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  # Set imagePullPolicy to Always to ensure Kubernetes always pulls the latest image
---
apiVersion: v1
kind: Service
metadata:
  name: wemealkit-service
  namespace: wemealkit
spec:
  selector:
    app: wemealkit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wemealkit-ingress
  namespace: wemealkit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: api.wemealkit.shop  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wemealkit-service
            port:
              number: 8080
  - host: api.jinnie.ddns.net  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wemealkit-service
            port:
              number: 8080
  tls:
  - hosts:
    - api.wemealkit.shop  # Replace with your actual domain
    secretName: wemealkit-tls
  - hosts:
    - api.jinnie.ddns.net  # Replace with your actual domain
    secretName: wemealkitddns-tls