#v1 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wemealkit-deployment
  namespace: wemealkit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wemealkit
  template:
    metadata:
      labels:
        app: wemealkit
    spec:
      containers:
      - name: wemealkit
        image: daikmasa/wemealkit:e1bb778
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  # Set imagePullPolicy to Always to ensure Kubernetes always pulls the latest image
---
apiVersion: v1
kind: Service
metadata:
  name: wemealkit-service
  namespace: wemealkit
spec:
  selector:
    app: wemealkit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: wemealkit-ingress
  namespace: wemealkit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: api.wemealkit.ddns.net  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wemealkit-service
            port:
              number: 8080
  tls:
  - hosts:
    - api.wemealkit.ddns.net  # Replace with your actual domain
    secretName: wemealkit-tlss
---
#redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: wemealkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: "000000Long@"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: wemealkit
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30007  # Optional: specify a port in the range 30000-32767
  selector:
    app: redis

---
# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: wemealkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # RabbitMQ main port
        - containerPort: 15672 # RabbitMQ management port
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "guest"
        - name: RABBITMQ_DEFAULT_PASS
          value: "guest"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        emptyDir: {}
---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: wemealkit
spec:
  type: NodePort
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 30008  # Optional: specify a port in the range 30000-32767
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 30009  # Optional: specify a port in the range 30000-32767
  selector:
    app: rabbitmq

---
# Ingress for RabbitMQ Management
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  namespace: wemealkit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
  - host: rabbitmq.wemealkit.ddns.net  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-service
            port:
              number: 15672
  tls:
  - hosts:
    - rabbitmq.wemealkit.ddns.net  # Replace with your actual domain
    secretName: rabbitmq-tls
