
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: contains(github.event.head_commit.message, 'deploy')
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: |
        -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAqdgP6enXqrQ8BoMEV9JGF9rBWAp2XzJL2evlFBWvdwCZky9hKs14
jqv2+QpQp3EFj3cpKr7i/1zc9IIUo7/5Ip2WVXzn/WEeGTNtJTL3NOD30WJSrIMFeTM6tT
Dzjy5Fxlana6C09hDKDhpxkCWqIjTdj98h6nd227EhqStesdcVnCJNGK/lbXrk8OkIlOjA
J50FhIfwpBrAu+wMxvoMa+Pm7352nitJxJFfAbokOG7Kfb9VD3Ync1YSXOqpFB+43+bQz3
q+BlmJ163pZ6FugOiALsZQsJ18ikt3MgU4nhWtGocbWaf9R9I75cw497E2pGdM/ZmyUNq8
TJZRO+qzUF3Z4JKFc+85bXY5nphkZolWp4xi0Y4MmdcOZkl1p6hwVO6Xq8izIUCy9idpiy
7qUp8kr68/QehE8/hiT/aCLNpeGTDzpYoIkGDm7GSVoAAA9glq3MO39jabTTRwYEU3gsrw
3xJqe6PTbYaUDPi1gTOg6735nXbIPub/VZTz1ZQSNR2eEf/Galvg+Qzqylt7A7GzugUP//
YNfJQto42PTUsfywEv9WUGybfEcQ+g3DHeIO1kDemP5mmIde+LjFk31oxJJIPbbV39U2tJ
sRgnY1zxTRI4BIzTD0YXjatS+Tews35a92w242sACq8II8MvhCkGVELABK9D0JLH41dqO6
0AAAdQCs75PQrO+T0AAAAHc3NoLXJzYQAAAgEAqdgP6enXqrQ8BoMEV9JGF9rBWAp2XzJL
2evlFBWvdwCZky9hKs14jqv2+QpQp3EFj3cpKr7i/1zc9IIUo7/5Ip2WVXzn/WEeGTNtJT
L3NOD30WJSrIMFeTM6tTDzjy5Fxlana6C09hDKDhpxkCWqIjTdj98h6nd227EhqStesdcV
nCJNGK/lbXrk8OkIlOjAJ50FhIfwpBrAu+wMxvoMa+Pm7352nitJxJFfAbokOG7Kfb9VD3
Ync1YSXOqpFB+43+bQz3q+BlmJ163pZ6FugOiALsZQsJ18ikt3MgU4nhWtGocbWaf9R9I7
5cw497E2pGdM/ZmyUNq8TJZRO+qzUF3Z4JKFc+85bXY5nphkZolWp4xi0Y4MmdcOZkl1p6
hwVO6Xq8izIUCy9idpiy7qUp8kr68/QehE8/hiT/aCLNpeGTDzpYoIkGDm7GSVoAAA9glq
3MO39jabTTRwYEU3gsrw3xJqe6PTbYaUDPi1gTOg6735nXbIPub/VZTz1ZQSNR2eEf/Gal
vg+Qzqylt7A7GzugUP//YNfJQto42PTUsfywEv9WUGybfEcQ+g3DHeIO1kDemP5mmIde+L
jFk31oxJJIPbbV39U2tJsRgnY1zxTRI4BIzTD0YXjatS+Tews35a92w242sACq8II8MvhC
kGVELABK9D0JLH41dqO60AAAADAQABAAACABzkj1J60BAvUH3IGHtLH1bsBROR1hC8OOiV
x1bLGJodLUL7XqN+KDnXGbDEdzOA19IP0p49slaAKOtkXJf9rqdbmQkqcjmppYnidHkNSj
4B3k6NlCRaNppnY1+S9//9vmtu7tSxlk88zG6pQ3Pi4GYoyZ8xtW6SS5M0dxY09Us6HGg+
8pAWTih5bUxpTCcu0A99GATzbjWwgmSFk6fevjG1Z6IKyKmAEjDBDSE5VfOOr15EZ/c1Ia
FufTm2xrQQcG4QcSm2hvCEF12sLWZOcUK3KqUqYewlolvRWjHVbwv/gn7eiIHQQNdQtZVS
UEecqz+8/f0vQgUcrMc3lBKmCsJEetApjDsJq1ng9ckJnsjAHTCFllSGLlATE0PXh/qjRM
nGrJU9Jc0sVXMyxqpWPq0SbrNfo6CVma5cb8eF5gK24S/Snjx/IgSP5wjzKPJkiy9Hlwok
bhQ+1RDzkT5kXkOUq22uQEC10XSuB1ery2KofqoG1Ez8tpEbWv3n2JZ/4dmsMvEiHxRDbT
vmH1vMr6senJKoZ8A/+HAha6LsJ5eeK32+AqmGm0vsDWBsSAcgs7fSlWT6uEL1EXqrcLaf
fZOpLI228O38Wq7sEE842ui3s9YjtiJmayFimbSsGWgJyx0DUgis11vcrOqMBbooxDfBIX
hL8ruQgcWdK9J+zYjBAAABABqLgXnvnqj58WBaBmsLFmjfeDKq9/LmxGqA029judQDMVJI
O3QHiGV3IUdGhxqX0V1RY/OPiuM/AazFPKt/shn0bsLpulNhmX4pHEFgDpnErY2RCVpFqq
FLDQeLS6TozjYW8pgsMrmyIBIHAg9XLEthbiE7R9kyvHTUY9Pl9FHJmw5dquMVRSRf9Z9B
wX3ZCyFcHWLyHz8B6IXvUlY8pUtQND1457wh2psQ7rKxTDit+W1YGx9xpFoN4EXLS147vV
knEqq/Yk482pb/WUlkDULbPm7CcR/J/5dJ8l3qyD496e2rNk1XG7qi4UnYIs52BsTKERsb
b7YJizul84QKuIQAAAEBANUPXwxS2CpyNdvGsDi9GE72mwFHynBW1MaZlH1ev7VWIRUmhA
3Q81oMu+mpKp7b4k4ELkv03EgJxf2SerpSDeBqyBOfWCPwu8A/l+Kli0pyb6LCbo81Hhoz
Y+0aCqhPrJfRdgUXJqV+Sgc/uMMmBNDvnjTw4OAQaBCmU3rxMB/zsj/8UGxHrio+x14Taq
t5TYejFNnAcF0xuyoZkQWwOsx8F7LbJLsxHXp3Sj3uXNCrFikzD2oWnYOKt/jRxn40wIP5
4O8TxCmvNVP30bjWJyaciKsK/DBm6pFK0BFSuZTclKSgWof7EN5tj0Y33QlwpE7QrwUfwl
hW17yprEMFQe0AAAEBAMwTAAmoqTcgeGDZpxV48qVEA8bll5gUVXQJIO4AxzA2VgGs0CKm
Gk+kJ4iGeyqgUmf31oqJ7Cxrvt5dOr3B2pX/iiJcx0v2NZw8pqrqkCGe8nGDAKLINYGNlH
njy0k0ariIb+5MojgzBFCnB0zErFbQUBcJU5CjPBjCBRidk29HESN1E1ZgUY6l1+R8kk0L
x3ud3MRWvSG/xJv/dLdbXb9Q1mjQjsF0k5B1Oh2AnT+NQpGxRt9KILZzCf/PVrPFUemDKr
mFmygKGNyMZwSRULn19bgSPSrLbfqnjAw/Zyqp8YBsDbDHwtG3bczL1yQNUBhc9V0PhDrY
vVHUE+vwqMEAAAAWeW91cl9lbWFpbEBleGFtcGxlLmNvbQECAwQF
-----END OPENSSH PRIVATE KEY-----
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x  # Use the latest available .NET Core version

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: daikmasa
        password: 7LL@iArX?wpb6!; #${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker-compose -f WMK_BE_Core/docker-compose.yml build 
      
    - name: Tag Docker image with version
      run: docker tag wmkberecipesandplanscontroller:latest daikmasa/wemealkit:$(echo "${GITHUB_SHA:0:7}")

    - name: Push Docker image to Docker Hub
      run: |
        docker push daikmasa/wemealkit:$(echo "${GITHUB_SHA:0:7}")
    - name: switching from HTTPS to SSH
      run: |
        git remote set-url origin git@github.com:DanhThanhLe/WMK_BE_01.git
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        sed -i "s/image: daikmasa\/wemealkit:[0-9a-f]*$/image: daikmasa\/wemealkit:${GITHUB_SHA:0:7}/" k8s/config.yaml
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating yaml.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master

    # # Install the .NET Core workload
    # - name: Install .NET Core
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x
    # #test
    # - name: .net Test
    #   run: dotnet test WMK_BE_Core/WMK_BE_Test/WMK_BE_Test.csproj

    # - name: publish the application
    #   run: dotnet publish WMK_BE_Core/WMK_BE_Core.sln -c Release --force --output publishCode
    
    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: wemealkit.shop
    #     username: Administrator
    #     password: 000000Long@
    #     port: 22
    #     script:   NET STOP WAS /Y 
    # # Deploy to FTP
    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: api.wemealkit.shop
    #     username: Administrator
    #     password: 000000Long@
    #     local-dir: publishCode/
    #     server-dir: /
        
    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: wemealkit.shop
    #     username: Administrator
    #     password: 000000Long@
    #     port: 22
    #     script: NET START W3SVC
   
